-- Fixes: "null value in column id of relation birds violates not-null constraint"
-- The birds.id column had no DEFAULT, so inserts without an explicit id failed.
-- This attaches an identity sequence seeded above the current max id.
do $$
begin
  if not exists (
    select 1 from pg_attribute
    where attrelid = 'public.birds'::regclass
      and attname = 'id'
      and attidentity <> ''
  ) then
    alter table public.birds
      alter column id add generated by default as identity;
  end if;
end $$;

select setval(
  pg_get_serial_sequence('public.birds', 'id'),
  coalesce((select max(id) from public.birds), 0) + 1,
  false
);
